---
# =================================================
# Install Prometheus
# =================================================
- name: Download Prometheus
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ PROMETHEUS_VERSION }}/prometheus-{{ PROMETHEUS_VERSION }}.linux-amd64.tar.gz"
    dest: "/tmp/prometheus.tar.gz"

# =================================================
# Extract Tarball
# =================================================
- name: Extract Prometheus tarball
  unarchive:
    src: "/tmp/prometheus.tar.gz"
    dest: "/opt"
    remote_src: yes

# =================================================
# Check
# =================================================
- name: Check if /opt/prometheus exists
  stat:
    path: /opt/prometheus
  register: prometheus_dir

# =================================================
# Rename Folder
# =================================================
- name: Rename Prometheus directory
  command: mv /opt/prometheus-{{ PROMETHEUS_VERSION }}.linux-amd64 /opt/prometheus
  when: not prometheus_dir.stat.exists

# =================================================
# Create Prometheus SystemD Service File
# =================================================
- name: Create a Prometheus systemd service file
  copy:
    dest: "/etc/systemd/system/prometheus.service"
    content: |
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=root
      Group=root
      Type=simple
      ExecStart=/opt/prometheus/prometheus \
        --config.file=/opt/prometheus/prometheus.yml \
        --storage.tsdb.path=/opt/prometheus/data \
        --web.console.templates=/opt/prometheus/consoles \
        --web.console.libraries=/opt/prometheus/console_libraries

      [Install]
      WantedBy=multi-user.target

# =================================================
# Create Prometheus Configuration File
# =================================================
- name: Create Prometheus configuration file
  copy:
    dest: "/opt/prometheus/prometheus.yml"
    content: |
      global:
        scrape_interval: 15s

      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']

        - job_name: 'node_exporter'
          static_configs:
            - targets: {{ TARGETS }}
  notify:
    - restart_prometheus
